### ISSUE TITLE
Setup testing regime

### ISSUE THREAD

**Issue by arnoweiss** [admin-shell-io/java-generator#13]
Afaik, there really isn't a good way to test this repo. I couldn't find any unit tests which is probably why the test-action [really isn't doing](https://github.com/admin-shell-io/java-generator/actions/runs/1816877040) anything right now:

https://github.com/admin-shell-io/java-generator/blob/0d37d2240fedd48cc5042248cdc92e8924d6233c/.github/workflows/maven-run-tests.yml#L24

**Comment by sebbader** [comment]
Suggestion: uncomment the mvn package line and do a checkout of the aas-spec before --> Will execute a test run of the pipeline.

**Comment by sebbader** [comment]
Follow-up activities will happen at https://github.com/eclipse-digitaltwin/aas4j-model-generator/issues/8
